const Images = {
    icons: {
        google: require('./images/ic_google.png'),
        facebook: require('./images/ic_facebook.jpg'),
        keyboard: require('./images/ic_keyboard.png'),
        filter: require('./images/ic_filter.png'),
        arrow_down: require('./images/ic_arrow_down.png'),
        arrow_right: require('./images/ic_arrow_right.png'),
        ic_company_1: require('./images/Loghi06.png'),
        ic_company_2: require('./images/lg_mark_ebike_2.png'),
        ic_company_3: require('./images/lg_mark_ebike_3.png'),
        ic_company_4: require('./images/lg_mark_ebike_4.png'),
        ic_company_5: require('./images/lg_mark_ebike_5.png'),
        ic_company_6: require('./images/lg_mark_motori_1.png'),
        ic_company_7: require('./images/lg_mark_motori_5.png'),
        ic_company_8: require('./images/lg_mark_motori_4.png'),
        ic_company_9: require('./images/lg_mark_motori_2.png'),
        ic_company_10: require('./images/lg_mark_motori_3.png'),
        ic_badge_empty: require('./images/bdg_star_empty.png'),
        ic_close: require('./images/ic_close.png'),
        ic_arrow_left: require('./images/ic_arrow_left.png'),
        ic_calendar: require('./images/ic_calendar.png'),
        ic_plus: require('./images/btn_plus_circle.png'),
        ic_minus: require('./images/btn_minus_circle.png'),
        ic_arrow_down: require('./images/arrow_down.png'),
        ic_info_green: require('./images/ic_info.jpg'),
        ic_triangle_down: require('./images/triangle-down.png'),
        ic_triangle_up: require('./images/Triangle.png'),
        ic_graph: require('./images/ic_graph.png'),
        ic_graph_lg: require('./images/ic_graph_lg.png'),
        ic_battery: require('./images/ic_battery.png'),
        ic_line: require('./images/line.png'),
        ic_plus_circle: require('./images/ic_plus.png'),
        ic_heart: require('./images/ic_heart_border.png'),
        ic_heart_red: require('./images/ic_heart_red.png'),
        ic_compare: require('./images/ic_footer_compare.png'),
        ic_share: require('./images/ic_share.png'),
        ic_info_black: require('./images/ic_info_sm_black.jpg'),
        ic_connect: require('./images/ic_connector.png'),
        ic_light: require('./images/ic_lightning_border.png'),
        ic_volt: require('./images/ic_volt.png'),
        ic_battery_lg: require('./images/ic_battery_lg.png'),
        ic_velocity: require('./images/ic_velocity_meter.png'),
        ic_linkedin: require('./images/ic_social_linkedin.png'),
        ic_alpha: require('./images/ic_alpha.png'),
        ic_twitter: require('./images/ic_twitter.png'),
        ic_whatsapp: require('./images/ic_whatsapp.png'),
        ic_facebook: require('./images/ic_facebook_full.png'),
        ic_close_sm: require('./images/ic_close_sm.png'),
        ic_home: require('./images/ic_footer_home.png'),
        ic_news: require('./images/ic_footer_news.png'),
        ic_profile: require('./images/ic_footer_profile.png'),
        ic_ebike: require('./images/ic_footer_ebike_finder.png'),

    },
    background: {
        logo: require('./images/logo.png'),
        title: require('./images/bicilive.it.png'),
        homeLogo: require('./images/img_bike_xduro.png'),
        subtitle: require('./images/img_title.png'),
        bike_logo: require('./images/img_bike_haibike.png'),
        bike_logo1: require('./images/img_bike_atala.png'),
        bike_logo2: require('./images/img_bike_bianchi.png'),
        address: require('./images/mountainbike.biciliv.png'),
    },
    btn: {
        bike_finder: require('./images/btn_ebike_finder.png'),
        news_finder: require('./images/btn_news_finder.png'),
        btn_back: require('./images/btn_back_half_circle.png')
    }
};

export default Images;
